#!/bin/sh -e

. /usr/share/debconf/confmodule
. /usr/share/arrowhead/conf/ahconf.sh

USER=$(logname)
HOME=$(eval echo "~$USER")

# Get installation type
db_input high arrowhead-common/install_type || true
db_go || true
db_get arrowhead-common/install_type; INSTALL_TYPE="$RET"

# User dialog
case ${INSTALL_TYPE} in
    "Authorized" )
        if [ ! -f /etc/arrowhead/cert/cloud.p12 ]; then
            # Set default path for cloud certificate
            db_get arrowhead-common/cloud_cert;
            if [ -z "$RET" ]; then
                db_set arrowhead-common/cloud_cert "${HOME}/cloud.p12"
            fi

            # Set default path for master certificate
            db_get arrowhead-common/master_cert; master_cert=$RET
            if [ -z "$RET" ]; then
                db_set arrowhead-common/master_cert "${HOME}/master.crt"
            fi

            # User dialogs
            db_input critical arrowhead-common/cloud_cert || true
            db_input critical arrowhead-common/cloud_alias || true
            db_input critical arrowhead-common/cloud_password || true
            db_input critical arrowhead-common/master_cert || true
        fi
        ;;

    "Detached" )
        # User dialogs
        db_input high arrowhead-common/cloudname || true
        db_input high arrowhead-common/operator || true
        db_input high arrowhead-common/company || true
        db_input high arrowhead-common/country || true
        ;;

    * )
        echo "Unexpected install type"
        exit 1
        ;;
esac

# Get certificate password
if [ -z "${AH_PASS_CERT}" ]; then
    db_input high arrowhead-common/cert_password || true
fi

# Get database password
if [ -z "${AH_PASS_DB}" ]; then
    db_input high arrowhead-common/mysql_password || true
fi

# Run dialogs
db_go || true

# Create user
adduser --system --no-create-home --group arrowhead

# Create directories
mkdir -p /etc/arrowhead/cert/
if [ ! -d /var/log/arrowhead ]; then
    mkdir -p /var/log/arrowhead
    chown arrowhead:adm /var/log/arrowhead
    chmod 750 /var/log/arrowhead
fi

# Reload global variables
. /usr/share/arrowhead/conf/ahconf.sh

# Generate certificate password (if required)
if [ -z "${AH_PASS_CERT}" ]; then
    PASS="$(openssl rand -base64 12)"
    db_set arrowhead-common/cert_password ${PASS}
fi

# Generate database password (if required)
if [ -z "${AH_PASS_DB}" ]; then
    PASS="$(openssl rand -base64 12)"
    db_set arrowhead-common/mysql_password ${PASS}
fi

# Reload global variables
. /usr/share/arrowhead/conf/ahconf.sh

# Do actions based on install type
case ${INSTALL_TYPE} in
    "Authorized" )
        if [ ! -f /etc/arrowhead/cert/cloud.p12 ]; then
            # Get additional variables
            db_get arrowhead-common/cloud_cert; cloud_cert=$RET
            db_get arrowhead-common/cloud_alias; cloud_alias=$RET
            db_get arrowhead-common/cloud_password; cloud_password=$RET
            db_get arrowhead-common/master_cert; master_cert=$RET

            # Store cloud certificate
            keytool -importkeystore \
                -srckeypass ${cloud_password} \
                -destkeypass ${AH_PASS_CERT} \
                -srcstorepass ${cloud_password} \
                -deststorepass  ${AH_PASS_CERT} \
                -srcalias ${cloud_alias} \
                -destalias cloud \
                -srckeystore "${cloud_cert}" \
                -destkeystore "/etc/arrowhead/cert/cloud.p12" \
                -deststoretype PKCS12
            chown :arrowhead "/etc/arrowhead/cert/cloud.p12"
            chmod 640 "/etc/arrowhead/cert/cloud.p12"

            # Store master certificate
            cp "${master_cert}" "/etc/arrowhead/cert/master.crt"
            chown :arrowhead "/etc/arrowhead/cert/master.crt"
            chmod 640 "/etc/arrowhead/cert/master.crt"

            # Extract data from CN field
            subject=$(keytool -list -keystore "/etc/arrowhead/cert/cloud.p12" -storepass ${AH_PASS_CERT} -v -alias cloud | grep "Owner:" | head -n1 | sed 's|Owner: ||')
            cloud_name=$(echo "${subject}" | sed 's|^.*CN=\([^.]*\)\.\([^.]*\)\.\([^.]*\)\.\([^,]*\),.*$|\1|')
            operator=$(echo "${subject}" | sed 's|^.*CN=\([^.]*\)\.\([^.]*\)\.\([^.]*\)\.\([^,]*\),.*$|\2|')
            company=$(echo "${subject}" | sed 's|^.*CN=\([^.]*\)\.\([^.]*\)\.\([^.]*\)\.\([^,]*\),.*$|\3|')
            country=$(echo "${subject}" | sed 's|^.*CN=\([^.]*\)\.\([^.]*\)\.\([^.]*\)\.\([^,]*\),.*$|\4|')

            # Store data
            db_set arrowhead-common/cloudname ${cloud_name}
            db_set arrowhead-common/operator ${operator}
            db_set arrowhead-common/company ${company}
            db_set arrowhead-common/country ${country}
        fi
        ;;

    "Detached" )
        # Generate master and cloud certificates
        ah_cert /etc/arrowhead/cert master "arrowhead.eu"
        ah_cert_export "/etc/arrowhead/cert" master "/etc/arrowhead/cert"
        ah_cert_signed /etc/arrowhead/cert cloud "${AH_CLOUD_NAME}.${AH_OPERATOR}.arrowhead.eu" /etc/arrowhead/cert master
        ;;

    * )
        echo "Unexpected install type"
        exit 1
        ;;
esac

# Trust the cloud certificate
ah_cert_trust /etc/arrowhead/cert /etc/arrowhead/cert cloud
